### ISSUE TITLE
reconnect

### ISSUE THREAD

**Issue by tomuGo** [vdalex25/WebRtcPlayer#1]
if the stream is close,and then restart.how to make the js reconnect

**Comment by vdalex25** [comment]
you can restart same stream or load new using `load()` method
```js
player.load(stream_UUID)
```

**Comment by tomuGo** [comment]
> you can restart same stream or load new using `load()` method
> 
> ```js
> player.load(stream_UUID)
> ```

ths for reply,but how do you know that the stream is  reconnected in webrtcPlay.js

**Comment by vdalex25** [comment]
i add new commit https://github.com/vdalex25/WebRtcPlayer/commit/9851a19dcde50e1e716af93c011e89dc808dd638

now create new player 
```js
let player = new WebRtcPlayer(videoelement, stream_UUID,{
  onStatusChange:(status)=>{
    switch (status) {
      case "disconnected":
        console.log("Disconnecting...");
        //make something for reload stream
        break;
      default:
        console.log("Unknown");
        break;
    }
  }
});
```
and there is list of statuses
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState

**Comment by tomuGo** [comment]
> i add new commit [9851a19](https://github.com/vdalex25/WebRtcPlayer/commit/9851a19dcde50e1e716af93c011e89dc808dd638)
> 
> now create new player
> 
> ```js
> let player = new WebRtcPlayer(videoelement, stream_UUID,{
>   onStatusChange:(status)=>{
>     switch (status) {
>       case "disconnected":
>         console.log("Disconnecting...");
>         //make something for reload stream
>         break;
>       default:
>         console.log("Unknown");
>         break;
>     }
>   }
> });
> ```
> 
> and there is list of statuses https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState

ths very much!!
