### ISSUE TITLE
Multiple rtsp streams on a webpage

### ISSUE THREAD

**Issue by DeanShandlerSL** [vdalex25/WebRtcPlayer#2]
Hi,
Thanks for making this player. Is it possible to simultaneously create multiple players that show different rtsp streams on a single webpage? And if so, how do I go by doing so? Will I need 3 different RTSPtoWEBRTC servers running?

**Comment by vdalex25** [comment]
Hi!
No, only one running server is needed
for example for 3 different player
```html
<script src="webrtcplayer.js"></script>

<video id="videoelement_1" autoplay controls muted style="width:600px;"></video>
<video id="videoelement_2" autoplay controls muted style="width:600px;"></video>
<video id="videoelement_3" autoplay controls muted style="width:600px;"></video>


<script>
WebRtcPlayer.setServer('localhost:8083');

let players= {
  first: new WebRtcPlayer('videoelement_1','H264_PCMALAW'),
  second: new WebRtcPlayer('videoelement_2','H264_PCMALAW'),
  third: new WebRtcPlayer('videoelement_3','H264_PCMALAW'),
}
</script>
```
and then for control
```js
players.second.load(stream_UUID);
```

**Comment by DeanShandlerSL** [comment]
Hey,
thanks for the quick reply. this really helps but how to configure 1 server with multiple RTSP streams?
this way you suggested makes the same stream appear 3 times.

**Comment by vdalex25** [comment]
[here is docs for config RTSPtoWEBRTC server](https://github.com/deepch/RTSPtoWebRTC#edit-file-configjson)

demo1, demo2, demo3 - it`s stream_UUID

**Comment by DeanShandlerSL** [comment]
thanks a lot!
