### ISSUE TITLE
Player doesnt load when we remove "muted" attribute from Video element

### ISSUE THREAD

**Issue by hiren3897** [vdalex25/WebRtcPlayer#6]
Hello,

I have used your webrtc.js to implement the RTSPTOWebRTC solution

I have a strange behaviour on my side 

if I remove the muted attribute from the HTMLVideoElement the player doesn't load

if I add it then it works

I have a rtsp stream with audio codec OPUS 

can you please help me?

**Comment by vdalex25** [comment]
Hi, not loaded or not  start autoplay?
here about autoplay video with sound https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide

**Comment by hiren3897** [comment]
Hi thanks for the quick response :)

```html
<div class="hexa-webrtc-container" style="max-width: 50em;">
    <video id="videoElem" class="hexa-webrtc-video hexa-webrtc-show" autoplay muted></video>
</div>
```
if I keep the muted attribute the player is loaded perfectly

but if I remove the `muted` attribute the player is not loaded

```html
<div class="hexa-webrtc-container" style="max-width: 50em;">
    <video id="videoElem" class="hexa-webrtc-video hexa-webrtc-show" autoplay></video>
</div>
```

**Comment by vdalex25** [comment]
browser policy prohibits playing video with sound if the user has not interacted with the page directly

player is loaded but you should  click play by yourself  - autoplay not working with sound

**Comment by hiren3897** [comment]
Yes, I am aware of that

but it should atleast load the player without audio no?

So every time we have to start the video muted? I want to start the video with audio BUT in your demo mentioned below

 here: https://github.com/deepch/RTSPtoWebRTC/blob/master/web/templates/player.tmpl#L29

Even if I remove the muted attribute it works!!

**Comment by vdalex25** [comment]
in that project, when the page loads, the video is loaded without an audio track, and then you click on the button to play the video with the audio track, and by doing so, you do an explicit action and the video plays with sound

is there any errors or warning in console?

**Comment by hiren3897** [comment]
hello, Thanks for the info

Yes,  As I am creating my own UI so I have to keep autoplay and muted attribute and let the user unmute it
Thanks :) for your work and help
